name: simple_dependency_injection
description: Simple is an dependency Injection management
version: 1.0.0
repository: https://github.com/Ispx/simple.git

environment:
  sdk: ^3.9.3


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
